//
//  Food.swift
//  NationUp
//
//  Created by Revarino Putra on 02/05/21.
//

import Foundation

struct Food {
    var image: String?
    var name: String?
    var description: String?
}

let jakartaFoods: [Food] = [
    Food(image: "keraktelor", name: "Kerak Telor", description: "The term gado or the verb menggado means to consume something without rice. Gado-gado in Indonesian literally means \"mix-mix\" since it is made of a rich mixture of vegetables such as potatoes, longbeans, bean sprouts, spinach, chayote, bitter gourd, corn and cabbage, with tofu, tempeh and hard-boiled eggs, all mixed in peanut sauce dressing, sometimes also topped with krupuk and sprinkles of fried shallots. Gado-gado is different from lotek atah or karedok which uses raw vegetables. Another similar dish is the Javanese pecel. Gado-gado is widely sold in almost every part of Indonesia, with each area having its own modifications.\n\n The sauce is made of fried crushed savory peanuts, sweet palm sugar, garlic, chilies, salt, tamarind and a squeeze of lime.[1] Gado-gado is generally freshly made, sometimes in front of the customers to suit their preferred degree of spiciness, which corresponds to the amount of chili pepper included."),
    Food(image: "gadogado", name: "Gado-gado", description: "Lorem ipsum sir dolor amet"),
    Food(image: "ketoprak", name: "Ketoprak", description: "The etymology of the name ketoprak is unknown, and its name similarity to the Javanese folk-drama is peculiar. However, according to popular Betawi tradition, ketoprak was actually derived from the acronym of its ingredients; which are ket from ketupat, to from tahu and toge, and prak from digeprak (Betawi for: \"mashed\" or \"crushed\"), which describes the method on grounding garlic, chili pepper and peanut granules together to create the peanut sauce. It is also believed that a man who loved eating invented the dish because he grew tiresome of the food he had normally eaten. When he dropped the dish on to the floor, the plate made the sound \"ketuprak\", which is where he got the idea for the name.\n\n In addition to its unique name, ketoprak is also unique in that all the street vendors use the same design for their carts. The vendors arrange and use all their tools in the same manner. A ketoprak wagon always has a stainless pan, a frying pan at the end of the cart, a used biscuit can for crackers, and a wooden pestle and mortar.\n\n Today, ketoprak is often associated with Jakarta as the dish is more easily available in this city compared to others. However, there is a debate on whether or not it actually originated in Jakarta. Some has claimed that the dish was first made in Cirebon, while others say that it comes from Central Java. As of 2018, no one has discovered where the dish actually originated from."),
    Food(image: "sotobetawi", name: "Soto Betawi", description: "Soto Betawi is a type of soup that originates from the Jakarta area of Indonesia. In Indonesian food, soto is a term used for many different types of soup originating from across the country – and just about every region has their own version of soto.\n\n some soto recipe reflects the past condition of its people. Soto tangkar, which today is a meat soup, was mostly made from the broth of goat rib-cage bones (Betawi:tangkar) in the past because meat was expensive, or the common population of Batavia were too poor to afford some meat back then. The meat soup dish influenced various regions and each developed its own recipes, with the ingredients being highly localized according to available ingredients and local cooking traditions. As a result, rich variants of soto were developed across Indonesia.")
]

let bandungFoods: [Food] = [
    Food(image: "miekocok", name: "Mie Kocok", description: "Mie kocok (lit: \"shaken noodle\"), is an Indonesian beef noodle soup, specialty of Bandung city, West Java. The dish consists of noodles served in rich beef consommé soup, kikil (beef tendon), bean sprouts and bakso (beef meatball), kaffir lime juice, and sprinkled with sliced fresh celery, scallion and fried shallot. Some recipes might add beef tripe.\n\n In Indonesian the term kocok means \"shake\", and it refers to the method of softening and cooking the noodles by shaking the noodles placed in a handled porous tin container, while being simmered in hot water. The dish uses flat yellow noodles. \n\n To add taste and spiciness kecap manis (sweet soy sauce) and sambal might be added. A similar-named but slightly different chicken-based noodle dish from the neighboring city of Cirebon is called mie koclok."),
    Food(image: "seblak", name: "Seblak", description: "Seblak is an Indonesian savoury and spicy dish, originating from the Sundanese region, West Java, Indonesia. Made of wet krupuk (traditional Indonesian crackers) cooked with protein sources (egg, chicken, seafood or beef) in spicy sauce.\n\n The word seblak may have originated Sundanese that is Nyeblak or surprising, because it tastes spicy and rich in spices. Seblak also refers to ingredients of Sundanese cuisine, made from cikur or Galangal (Kaempferia galanga).\n\n In earlier days, the term seblak refer to hot and spicy spice mixture made from ground kencur (Kaempferia galanga) and chili pepper. It is also refer to a traditional hot and spicy crispy krupuk crackers originate from rural southern Cianjur area before the independence era, this food was an alternative food, which is now called as seblak kering (dry seblak) or krupuk seblak. However, today it is mostly refer to its wet and savoury version; the seblak basah."),
    Food(image: "serabi", name: "Serabi", description: "Serabi, also called surabi, srabi, also known in Thailand as khanom khrok, is an Indonesian pancake that is made from rice flour with coconut milk or shredded coconut as an emulsifier. Most of traditional serabi tastes sweet, as the pancake is usually eaten with kinca or thick golden-brownish-colored coconut sugar syrup. However, another savoury version also existed that uses oncom toppings. Different provinces in various Asian countries have their own serabi recipes corresponding to local tastes.\n\n Both the cities of Bandung and Solo are famous for their versions of serabi. Bandung surabi is drier and firmer with a pancake-like consistency, and today is well known for the rich variant of toppings, most are recently developed fusion recipes.")
]

let semarangFoods: [Food] = [
    Food(image: "lumpia", name: "Lumpia", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda."),
    Food(image: "tahugimbal", name: "Tahu Gimbal", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.")
]

let jogjaFoods: [Food] = [
    Food(image: "gudeg", name: "Gudeg", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda."),
    Food(image: "bakpia", name: "Bakpia Pathok", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.")
]

let bogorFoods: [Food] = [
    Food(image: "rotiunyil", name: "Roti Unyil", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda."),
    Food(image: "sotomie", name: "Soto Mie", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.")
]

let malangFoods: [Food] = [
    Food(image: "baksomalang", name: "Bakso Malang", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda."),
    Food(image: "oremorem", name: "Orem-orem", description: "Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nam liber te conscient to factor tum poen legum odioque civiuda.")
]

func getFoods() -> [Food] {
    return jakartaFoods
}
